### ISSUE TITLE
How would I go about removing the Footer line

### ISSUE THREAD

**Issue by awalvie** [aravindballa/gatsby-theme-andy#16]
![image](https://user-images.githubusercontent.com/35740094/87230953-c7beb700-c3d0-11ea-94e1-b9514081f7a6.png)

I would like to remove the bottom half of the content from the theme. I took a look at both [component shadowing](https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/) and [extending component shadowing](https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/) and as I understand I'm supposed to make a `Footer.js` file at `./src/gataby-theme-andy/components`. I don't really have any idea how to write JS though, so can somebody help me in figuring out what the content of the file should look like?

**Comment by awalvie** [comment]
I tried this 

```js
import React from 'react';
import ReferredBlock from 'gatsby-theme-andy';

export default function Footer() {
	return (<Box p={3} sx={{borderRadius: 2}} mb={2} bg="accent" color="text-light">
		<ReferredBlock references={references} />
	</Box>)
}
```

and I received 
![image](https://user-images.githubusercontent.com/35740094/87231210-c2fb0280-c3d2-11ea-842e-1f61c30e4415.png)

**Comment by aravindballa** [comment]
You were almost there. Try this

```jsx
import React from 'react';
import { Box, jsx } from 'theme-ui';
import ReferredBlock from 'gatsby-theme-andy/src/components/ReferredBlock';

export default function Footer({ references }) {
  return (
    !!references.length && (
      <Box p={3} sx={{ borderRadius: 2 }} mb={2} bg="accent" color="text-light">
        <ReferredBlock references={references} />
      </Box>
    )
  );
}
```

**Comment by awalvie** [comment]
works like a charm! Thanks!
