### ISSUE TITLE
Not getting the sidebar once notes are stacked

### ISSUE THREAD

**Issue by kevindstevens1010** [aravindballa/gatsby-theme-andy#20]
Hello! Great theme, thank you for putting this together.  

I'm having an issue getting the sidebar on the left as notes stack up.  Your site works fine, so I know it has to be something on my end. 

I've attached an image to help in case I did not describe it well. 

![Screen Shot 2020-07-16 at 7 57 24 PM](https://user-images.githubusercontent.com/67278603/87736852-df19ed80-c79e-11ea-9eaa-40261add044c.png)

**Comment by aravindballa** [comment]
I didn't update my website with the latest version of this theme yet. Turns out, this broke while fixing the mobile views.

Should be fixed in the latest version.
