### ISSUE TITLE
Getting a "TypeError: note.childMdx is null" on running yarn develop

### ISSUE THREAD

**Issue by kprohith** [aravindballa/gatsby-theme-andy#28]
```
warning The GraphQL query in the non-page component "C:/Users/rohith/Documents/GitHub/notes-digital-garden/node_modules/@aengusm/gatsby-theme-brain/src/templates/brain.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
```

![image](https://user-images.githubusercontent.com/43675446/98435838-61d30980-20fc-11eb-996d-b53bd42f4e21.png)

**Comment by aravindballa** [comment]
Which version of node are you on?

**Comment by kalmir** [comment]
Hi, Aravind, that happened to me too :(

Node v15.5.1.

**Comment by kalmir** [comment]
And after switching node to 12.20.1. 

<img width="1494" alt="Screenshot 2021-01-12 at 11 11 53" src="https://user-images.githubusercontent.com/15029766/104308678-f5440480-54c8-11eb-86bf-0d854f0f07df.png">

**Comment by kalmir** [comment]
Eventually I made it work. Not sure if it was still the same problem as reported above, but the last thing I needed to "fix" was having some md files already in _content_ directory. Otherwise an error is thrown.

**Comment by aravindballa** [comment]
Cool. I'll add this to readme in a while.
