### ISSUE TITLE
mobile view at notes.andymatuschak.org tends to use the rightmost view

### ISSUE THREAD

**Issue by simkimsia** [aravindballa/gatsby-theme-andy#3]
if you go to this link https://notes.andymatuschak.org/About_these_notes?stackedNotes=z2kr7QrJczqYyfwLFcv1FLEUMdVTsgfYSdFXA

the full window desktop view looks like this

![image](https://user-images.githubusercontent.com/245021/83121906-7fd81f00-a105-11ea-9baf-4421eccd7977.png)

When resized it becomes the right most

![image](https://user-images.githubusercontent.com/245021/83121951-8b2b4a80-a105-11ea-95bf-16f9f210620a.png)

When i attempt to do the same 

![image](https://user-images.githubusercontent.com/245021/83122013-a0a07480-a105-11ea-89f1-1775f455212c.png)

full view works

but the resized adopts the leftmost

![image](https://user-images.githubusercontent.com/245021/83122067-b31aae00-a105-11ea-8c7c-99779a89594e.png)

**Comment by aravindballa** [comment]
Yup, working on this. Aiming to fix this in the new release along with #7
