### ISSUE TITLE
Shadow BrainNote.js to remove file title as note header

### ISSUE THREAD

**Issue by awalvie** [aravindballa/gatsby-theme-andy#32]
Hey, I use this repository to host markdown files written in Obsidian.md. Whenever a new note is rendered the note title is defaulted to be the file title. [This](https://github.com/aravindballa/gatsby-theme-andy/blob/3423cb713a1265127e204be9f93e6391a7a1a811/src/components/BrainNote.js#L32) seems to be the portion of the code that is doing the rendering. I'm not too experienced with JS and shadowing so I was hoping someone could help me with what the right code would be to remove this.

**Comment by technolaaji** [comment]
when you are creating a note, add in the frontmatter at the top of your markdown file

```
---
title: 'My Personal Codex'
---

```

it will change the name of the title from the file name to the title in the frontmatter
