### ISSUE TITLE
Installation steps require a change in package.json as well?

### ISSUE THREAD

**Issue by simkimsia** [aravindballa/gatsby-theme-andy#4]
Does it require the package.json to adopt the following wholesale for the theme to work?

```js
"dependencies": {
    "@tippyjs/react": "^4.0.2",
    "gatsby": "^2.20.36",
    "gatsby-plugin-postcss": "^2.2.4",
    "gatsby-theme-andy": "^0.1.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.0.0"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^2.1.2",
    "autoprefixer": "^9.7.6",
    "tailwindcss": "^1.3.5"
  },
```

and what about the src folder? Do the components inside also need to be created from scratch?

## src folder

I am comparing https://github.com/aravindballa/notes.aravindballa.com/tree/master/src against the src in this repo https://github.com/aravindballa/gatsby-theme-andy/tree/master/src

**Comment by thisizkp** [comment]
@simkimsia I think the theme gives you the functionality of "stacked pages" and "interconnected notes" (backlink support). Apart from that, it's on the consumer/user to develop every custom component as one likes.

Yeah, If you are just using the theme without any custom components, it'll look like this.
<img width="1675" alt="Screenshot 2020-05-29 at 16 20 40" src="https://user-images.githubusercontent.com/4737336/83252133-58965600-a1c8-11ea-9238-cfccaa4764b3.png">

If you want the theme closer to how Aravind has done it, then we need to copy those custom components as well.

**Comment by simkimsia** [comment]
Yup I agree

I was exchanging DM with Aravind directly earlier today

Will update his advice here and then close this issue

**Comment by aravindballa** [comment]
Yes that’s correct @thisizkp, thanks.

I think I should mentioning this part in readme. I’ll close this issue for now and make it clear in the readme. Feel free to reopen if you’d like to discuss more.
