### ISSUE TITLE
Hot Reload Failure

### ISSUE THREAD

**Issue by thisizkp** [aravindballa/gatsby-theme-andy#6]
I think hot reload (or) fast refresh, whatever we are using doesn't seem to be working anymore.

I'm running `gatsby develop` and the changes are not being watched. Especially [[back-links]], every time I add a new backlink, I need to restart the server to view the changes.

I couldn't find anything in the readme. Do let me know if I need to set up some config for that or is this a known bug.

**Comment by aravindballa** [comment]
Fixed in `v0.1.4` as well. Thanks for raising an issue!
