### ISSUE TITLE
Adding rss to the site

### ISSUE THREAD

**Issue by thisizkp** [aravindballa/gatsby-theme-andy#8]
[Gatsby theme brain](https://www.gatsbyjs.org/packages/@aengusm/gatsby-theme-brain/) accepts the following options - `generateRSS`, `rssPath`, `rssTitle` to enable rss.

Whereas [Gatsby theme Andy](https://github.com/aravindballa/gatsby-theme-andy/blob/master/gatsby-config.js) doesn't seem to pass/override the options.

Is there anything that's blocking us from doing this? 🤔 

Let me know, will be happy to raise a PR for that.

**Comment by aravindballa** [comment]
Yes we would need to add those options in [gatsby-config](https://github.com/aravindballa/gatsby-theme-andy/blob/master/gatsby-config.js) and pass them down to gatsby-theme-brain.

I can think of anything that might be blocking us.
